"""empty message

Revision ID: 26dfb15fffeb
Revises: 7fb62e2ba68e
Create Date: 2021-01-13 17:01:51.548548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26dfb15fffeb'
down_revision = '7fb62e2ba68e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'message')
    # ### end Alembic commands ###
