"""empty message

Revision ID: 89f7a7fa37ac
Revises: 
Create Date: 2020-08-01 18:13:43.893749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89f7a7fa37ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asynchronous_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.Column('event_code', sa.String(), nullable=False),
    sa.Column('event_category', sa.String(), nullable=False),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cyclic_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_parsed', sa.Boolean(), nullable=False),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('item0', sa.REAL(), nullable=False),
    sa.Column('item1', sa.REAL(), nullable=False),
    sa.Column('item2', sa.REAL(), nullable=False),
    sa.Column('item3', sa.REAL(), nullable=False),
    sa.Column('item4', sa.REAL(), nullable=False),
    sa.Column('item5', sa.REAL(), nullable=False),
    sa.Column('item6', sa.REAL(), nullable=False),
    sa.Column('item7', sa.REAL(), nullable=False),
    sa.Column('item8', sa.REAL(), nullable=False),
    sa.Column('item9', sa.REAL(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('column_id', sa.String(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('device_item_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devices',
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parsed_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('item0_max', sa.REAL(), nullable=False),
    sa.Column('item0_min', sa.REAL(), nullable=False),
    sa.Column('item1_max', sa.REAL(), nullable=False),
    sa.Column('item1_min', sa.REAL(), nullable=False),
    sa.Column('item2_max', sa.REAL(), nullable=False),
    sa.Column('item2_min', sa.REAL(), nullable=False),
    sa.Column('item3_max', sa.REAL(), nullable=False),
    sa.Column('item3_min', sa.REAL(), nullable=False),
    sa.Column('item4_max', sa.REAL(), nullable=False),
    sa.Column('item4_min', sa.REAL(), nullable=False),
    sa.Column('item5_max', sa.REAL(), nullable=False),
    sa.Column('item5_min', sa.REAL(), nullable=False),
    sa.Column('item6_max', sa.REAL(), nullable=False),
    sa.Column('item6_min', sa.REAL(), nullable=False),
    sa.Column('item7_max', sa.REAL(), nullable=False),
    sa.Column('item7_min', sa.REAL(), nullable=False),
    sa.Column('item8_max', sa.REAL(), nullable=False),
    sa.Column('item8_min', sa.REAL(), nullable=False),
    sa.Column('item9_max', sa.REAL(), nullable=False),
    sa.Column('item9_min', sa.REAL(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parsed_logs')
    op.drop_table('devices')
    op.drop_table('device_items')
    op.drop_table('cyclic_logs')
    op.drop_table('asynchronous_logs')
    # ### end Alembic commands ###
