"""empty message

Revision ID: 8d0ce47cb472
Revises: 
Create Date: 2020-06-02 16:42:58.438101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d0ce47cb472'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asynchronous_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.Column('event_code', sa.String(), nullable=False),
    sa.Column('event_category', sa.String(), nullable=False),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cyclic_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.Column('flow', sa.REAL(), nullable=False),
    sa.Column('pven', sa.Integer(), nullable=False),
    sa.Column('pint', sa.Integer(), nullable=False),
    sa.Column('deltap', sa.Integer(), nullable=False),
    sa.Column('part', sa.Integer(), nullable=False),
    sa.Column('tven', sa.REAL(), nullable=False),
    sa.Column('tart', sa.REAL(), nullable=False),
    sa.Column('svo2', sa.REAL(), nullable=False),
    sa.Column('hct', sa.REAL(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cyclic_logs')
    op.drop_table('asynchronous_logs')
    # ### end Alembic commands ###
