"""empty message

Revision ID: bbd7220a4e22
Revises: 
Create Date: 2020-06-12 22:10:12.491545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbd7220a4e22'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asynchronous_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.Column('event_code', sa.String(), nullable=False),
    sa.Column('event_category', sa.String(), nullable=False),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cyclic_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_parsed', sa.Boolean(), nullable=False),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.Column('flow', sa.REAL(), nullable=False),
    sa.Column('pven', sa.Integer(), nullable=False),
    sa.Column('pint', sa.Integer(), nullable=False),
    sa.Column('deltap', sa.Integer(), nullable=False),
    sa.Column('part', sa.Integer(), nullable=False),
    sa.Column('tven', sa.REAL(), nullable=False),
    sa.Column('tart', sa.REAL(), nullable=False),
    sa.Column('svo2', sa.REAL(), nullable=False),
    sa.Column('hct', sa.REAL(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parsed_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.Column('speed_max', sa.Integer(), nullable=False),
    sa.Column('speed_min', sa.Integer(), nullable=False),
    sa.Column('flow_max', sa.REAL(), nullable=False),
    sa.Column('flow_min', sa.REAL(), nullable=False),
    sa.Column('pven_max', sa.Integer(), nullable=False),
    sa.Column('pven_min', sa.Integer(), nullable=False),
    sa.Column('pint_max', sa.Integer(), nullable=False),
    sa.Column('pint_min', sa.Integer(), nullable=False),
    sa.Column('deltap_max', sa.Integer(), nullable=False),
    sa.Column('deltap_min', sa.Integer(), nullable=False),
    sa.Column('part_max', sa.Integer(), nullable=False),
    sa.Column('part_min', sa.Integer(), nullable=False),
    sa.Column('tven_max', sa.REAL(), nullable=False),
    sa.Column('tven_min', sa.REAL(), nullable=False),
    sa.Column('tart_max', sa.REAL(), nullable=False),
    sa.Column('tart_min', sa.REAL(), nullable=False),
    sa.Column('svo2_max', sa.REAL(), nullable=False),
    sa.Column('svo2_min', sa.REAL(), nullable=False),
    sa.Column('hct_max', sa.REAL(), nullable=False),
    sa.Column('hct_min', sa.REAL(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parsed_logs')
    op.drop_table('cyclic_logs')
    op.drop_table('asynchronous_logs')
    # ### end Alembic commands ###
